### ISSUE TITLE
Adding item to another persons list

### ISSUE THREAD

**Issue by jt-zoovy** [visegripped/giftmanager#2]
When an item is added to another person's list, the list does not auto-update.

Steps to reproduce:
 1.  go to GM
 2.  select any other user than yourself
 3.  add an item to their list.

**Comment by visegripped** [comment]
Fixed.
https://github.com/visegripped/giftmanager/commit/9d82ba02829c9052a7fcb9f956b9ffa09497c8bc
https://github.com/visegripped/giftmanager/commit/6818abc24e7e2fb8c9a9a04fe36e3cbf657bb325
