### ISSUE TITLE
Item description not showing on new items

### ISSUE THREAD

**Issue by jt-zoovy** [visegripped/giftmanager#4]
Steps to reproduce:
 1.  go to GM
 2.  select any other user than yourself
 3.  add an item to their list with a description.
 4. click their name in the user list at the top to refresh the list.

Item description just shows a 1.  POST does appear to be sending it correctly.

**Comment by visegripped** [comment]
Fixed.
https://github.com/visegripped/giftmanager/commit/9d82ba02829c9052a7fcb9f956b9ffa09497c8bc
https://github.com/visegripped/giftmanager/commit/6818abc24e7e2fb8c9a9a04fe36e3cbf657bb325
