### ISSUE TITLE
removed items not coming off of list

### ISSUE THREAD

**Issue by jt-zoovy** [visegripped/giftmanager#5]
When an item is tagged as 'remove' from your own list, it maintains that tag, but remains on the list indefinitely.  Needs to come off after being tagged after 24 hours.

Steps to reproduce:
 1.  go to GM
 2.  select yourself
 3.  tag item as removed.

**Comment by visegripped** [comment]
Fixed:
https://github.com/visegripped/giftmanager/commit/9fe3f73b7c0a64a6fe8e09cb8bc58dc2a9372bf5
